In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os, glob

In [11]:
df = pd.read_csv("../../Data/all_data.csv")
df

,N,m0,dim,alpha_a,alpha_g,N_samples,Short_Cost_mean,Short_Cost_error,Short_BFS_mean,Short_BFS_error,R_Spearman_mean,R_Spearman_error,R_Newman_mean,R_Newman_error,ClusterCoefficient_mean,ClusterCoefficient_error
0,131072,2,1,0.0,2.0,11,6.156176,0.050776,5.995403,0.010487,0.286269,0.001646,-0.019361,0.002061,0.000598,0.000032
1,131072,2,1,1.0,2.0,11,2.741658,0.006697,6.678534,0.017627,0.306807,0.001629,-0.020456,0.003120,0.027528,0.000129
2,131072,2,1,2.0,1.0,112,31.749291,2.256164,9.897085,0.023250,0.419327,0.000416,0.106054,0.000944,0.375039,0.000124
3,131072,2,1,2.0,2.0,11,2.702028,0.010433,10.005388,0.026806,0.420642,0.001353,0.109811,0.002896,0.377341,0.000333
4,131072,2,1,2.0,3.0,11,1.872412,0.027835,10.264545,0.048833,0.421176,0.001241,0.109157,0.002793,0.377025,0.000323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,8192,2,4,5.0,2.0,601,4.525885,0.005537,5.668771,0.002199,0.338269,0.000785,-0.023159,0.000962,0.102881,0.000143
428,8192,2,4,6.0,2.0,601,4.478837,0.004030,6.088345,0.002276,0.369767,0.000782,0.016742,0.001018,0.155675,0.000171
429,8192,2,4,7.0,2.0,601,4.466564,0.003422,6.437145,0.002490,0.392480,0.000778,0.051483,0.001087,0.201056,0.000180
430,8192,2,4,8.0,2.0,602,4.474553,0.004607,6.711514,0.002655,0.407676,0.000766,0.078236,0.001125,0.233656,0.000190
431,8192,2,4,9.0,2.0,601,4.476717,0.003141,6.921011,0.002767,0.418855,0.000769,0.097949,0.001179,0.257788,0.000192

array([  4096,   8192,  16384,  32768,  65536, 131072])

In [ ]:
N_values = np.sort(df["N"].unique())
N = 131072
#alpha_a_values = []
m0, alpha_a = 2, 2
dim = 2
df_sub = df[(df['N']==N) & (df['m0']==m0) & (df['m0']==m0) & (df['alpha_a']==alpha_a) & (df['dim']==dim)]
df_sub

,N,m0,dim,alpha_a,alpha_g,N_samples,Short_Cost_mean,Short_Cost_error,Short_BFS_mean,Short_BFS_error,R_Spearman_mean,R_Spearman_error,R_Newman_mean,R_Newman_error,ClusterCoefficient_mean,ClusterCoefficient_error
20,131072,2,2,2.0,1.0,11,28.254627,1.298809,6.942148,0.054221,0.272290,0.003298,-0.042978,0.005196,0.020467,0.000113
21,131072,2,2,2.0,2.0,97,3.263218,0.002062,6.591468,0.003841,0.306211,0.000531,-0.026209,0.000901,0.028301,0.000054
22,131072,2,2,2.0,3.0,11,2.267241,0.001269,6.735164,0.009783,0.308953,0.001548,-0.026687,0.002304,0.031536,0.000139
23,131072,2,2,2.0,4.0,77,1.941847,0.000320,6.854107,0.002790,0.310701,0.000574,-0.026427,0.000815,0.033230,0.000053
24,131072,2,2,2.0,5.0,11,1.781863,0.000606,6.940135,0.008953,0.311043,0.001452,-0.026351,0.002231,0.034969,0.000220
25,131072,2,2,2.0,6.0,11,1.688129,0.000427,7.039931,0.010448,0.311940,0.001482,-0.028114,0.002022,0.036381,0.000116
26,131072,2,2,2.0,7.0,111,1.624952,0.000138,7.112888,0.003412,0.311430,0.000473,-0.030203,0.000672,0.037560,0.000058
27,131072,2,2,2.0,8.0,11,1.580722,0.000201,7.167234,0.011237,0.311491,0.001469,-0.030115,0.002121,0.038336,0.000199
28,131072,2,2,2.0,9.0,11,1.549105,0.000359,7.222934,0.010516,0.312082,0.001501,-0.031199,0.002155,0.039729,0.000128